feat(prysm): arm support
nix-community/ethereum.nix pull request #386
Opened 2023-09-27 12:29 UTC by dzmitry-lahoda

for https://github.com/nix-community/ethereum.nix/issues/284

Seems libs i patched are old, devs improved arm build in master. may be should update.

```
actions-runner@Ubuntu-2204-jammy-arm64-base:~/github.com/nix-community/ethereum.nix$ nix build .#prysm -L --show-trace
actions-runner@Ubuntu-2204-jammy-arm64-base:~/github.com/nix-community/ethereum.nix$ uname -a
Linux Ubuntu-2204-jammy-arm64-base 5.15.0-83-generic #92-Ubuntu SMP Mon Aug 14 09:34:05 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
actions-runner@Ubuntu-2204-jammy-arm64-base:~/github.com/nix-community/ethereum.nix$ 
```

2023-10-03 10:57 UTC, aldoborrero requested changes
Minor changes are requested that are mostly related to importing directly `lib` rather than `pkgs.lib`.

2023-10-03 10:57 UTC, aldoborrero commented on packages/libs/mcl/default.nix
> +  pkgs,
@dzmitry-lahoda Incorporate lib directly rather than using pkgs

2023-10-03 10:57 UTC, aldoborrero commented on packages/libs/bls/default.nix
> +  pkgs,
@dzmitry-lahoda use lib instead of importing pkgs

2023-10-03 10:59 UTC, aldoborrero commented
@dzmitry-lahoda thanks for contributing! Apart from the minor changes I requested, would you mind squashing all your commits and updating the commit message to be more like: "feat: add arm support to prysm"?

2023-10-05 17:09 UTC, merged

2023-10-05 21:23 UTC, dzmitry-lahoda commented
oh, sorry. missed. was occupied by ethereum testnet release. may be you used squash merge setting in github?