packages: add blutgang
nix-community/ethereum.nix pull request #471
Opened 2024-02-14 14:49 UTC by jhvst

Consider adding blutgang, a load balancer for Ethereum RPC calls into the repository.

The canary pre-release supports WS RPC in addition to HTTP RPC, for which the initial proposition is to add this pre-release package.

2024-02-15 15:19 UTC, aldoborrero requested changes
@jotto also ideally you should have to add the package to the list of `pkgs` you can find on `pkgs/default.nix` file by adding it to the `programs` and the `apps` attrset. Otherwise, CI doesn't build it; you cannot use it as a user with commands like `nix run` or `nix build`.

2024-02-15 15:19 UTC, aldoborrero commented on pkgs/blutgang/default.nix
> +  name = "blutgang";
@jhvst it should be `pname`

2024-02-16 16:34 UTC, jhvst commented on pkgs/blutgang/default.nix
> +  name = "blutgang";
Fixed in a new commit.

2024-02-16 16:54 UTC, aldoborrero commented on pkgs/blutgang/default.nix
> +  name = "blutgang";
Nice! Don't forget to add the pkg to `pkgs/default.nix`

2024-02-17 17:03 UTC, aldoborrero approved these changes

2024-02-17 17:06 UTC, merged