Implement Reth service module
nix-community/ethereum.nix pull request #531
Opened 2024-07-13 04:37 UTC by scottbot95

I tested this against Reth 1.0 (from #530), however I don't think the command line has changed since the current imported version (0.2.0-beta.6) so I opted to implement it against `main` instead of on top of my other PR.

I chose not to implement and integration test with a nixos vm because I felt it is mostly likely unecessary due to the extensive test coverage within Reth itself.

2024-07-15 11:19 UTC, aldoborrero commented
@scottbot95 and we will migrate soonish to Reth 1.0, so even if it doesn't work at all, it's not a problem to merge it now.

2024-07-15 11:20 UTC, aldoborrero requested changes
@scottbot95 only minor thing:

- Remove mdDoc as those are effectively deprecated.

2024-07-15 16:31 UTC, scottbot95 commented
Oh I didn't realize `mdDoc` isn't needed anymore. It got included since I just copied from another module, but I can remove them.

2024-07-19 09:31 UTC, aldoborrero approved these changes

2024-07-19 09:31 UTC, merged