feat: add statix for nix linting
nix-community/ethereum.nix pull request #71
Opened 2023-01-19 16:19 UTC by brianmcgee

2023-01-20 13:00 UTC, aldoborrero requested changes
See pending comments.

Also, I think we should include a shortcut within `nix/scripts.nix` to run easily the tool, in the same way, we can do with `, fmt`.

The rest of the PR looks good enough to me.

2023-01-20 13:00 UTC, aldoborrero commented on nix/checks.nix
> +          rm -rf source/.direnv # delete .direnv cache so nix-linter don't recurse it
@brianmcgee is there a way of specifying to ignore folders directly using static?

2023-01-20 15:17 UTC, brianmcgee commented on nix/checks.nix
> +          rm -rf source/.direnv # delete .direnv cache so nix-linter don't recurse it
I've added a `statix.toml` for controlling ignore patterns and simplified the checks integration

2023-01-20 15:18 UTC, brianmcgee commented
> Also, I think we should include a shortcut within `nix/scripts.nix` to run easily the tool, in the same way, we can do with `, fmt`.

A shortcut is not needed. Just run `statix` or `nix flake check`.

2023-01-20 16:46 UTC, aldoborrero submitted a review, later dismissed
LGTM

2023-01-23 09:40 UTC, aldoborrero approved these changes

2023-01-23 09:40 UTC, merged